"""Build GitHub Pages files from explicitly published lesson JSON, without secrets or DB."""
import json
import re
import shutil
from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED
from jinja2 import Environment, FileSystemLoader, select_autoescape
from docx_lessons import read_report
from course_packages import read_package

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / 'docs'


def build(output=OUTPUT):
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    env = Environment(loader=FileSystemLoader(ROOT / 'templates'), autoescape=select_autoescape(['html']))
    articles = []
    for file in sorted((ROOT / 'content').glob('lesson-*.json')):
        article = json.loads(file.read_text(encoding='utf-8'))
        if article.get('published') is True:
            article['id'] = article['week']
            articles.append(article)
    for file in sorted((ROOT / 'lessons').glob('*.docx')):
        if not file.name.startswith(('_', '~$')):
            raise ValueError(f'{file.name}: 請放進課程資料夾並命名 report.docx，搭配 lesson.json 與互動頁設定')
    for folder in sorted((ROOT / 'lessons').glob('*')):
        if folder.is_dir() and not folder.name.startswith(('_', '.')):
            try:
                article = read_package(folder)
                if article:
                    articles.append(article)
            except Exception as error:
                raise ValueError(f'無法匯入課程 {folder.name}: {error}') from error
    identifiers = set()
    for article in articles:
        identifier = article['id']
        if type(identifier) is not int or not 1 <= identifier <= 999:
            raise ValueError('課次必須是 1 到 999 的整數')
        if identifier in identifiers:
            raise ValueError(f'課次 {identifier:03d} 重複，請使用不同的檔名前綴')
        identifiers.add(identifier)
    articles.sort(key=lambda article: article['week'], reverse=True)
    # Remove pages generated by previous builds if they are no longer published.
    expected_pages = {'index.html'} | {f'courses/{a["id"]}/index.html' for a in articles}
    expected_pages |= {f'courses/{a["id"]}/lab/index.html' for a in articles if a.get('interactive') in ('kmeans', 'custom')}
    manifest = output / '.generated-pages.json'
    if manifest.exists():
        for old_page in set(json.loads(manifest.read_text(encoding='utf-8'))) - expected_pages:
            target = (output / old_page).resolve()
            if not target.is_relative_to(output.resolve()) or target.suffix != '.html':
                raise ValueError('Invalid generated page path')
            target.unlink(missing_ok=True)

    def write(template, path, prefix, **context):
        html = env.get_template(template).render(static_site=True, **context)
        # Relative URLs also work at https://user.github.io/repository/.
        html = re.sub(r'(href|src)="/(?!/)([^\"]*)"',
                      lambda m: f'{m[1]}="{prefix}{m[2]}"', html)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(html, encoding='utf-8')

    write('home.html', output / 'index.html', './', courses=articles)
    for article in articles:
        code = (ROOT / 'static/python/kmeans_lab.py').read_text(encoding='utf-8') if article.get('interactive') == 'kmeans' else ''
        write('report.html' if 'body_html' in article else 'detail.html', output / f'courses/{article["id"]}/index.html', '../../',
              course=article, article=article, interactive_code=code)
        if article.get('interactive') in ('kmeans', 'custom'):
            write('custom_lab.html' if article['interactive'] == 'custom' else 'lab.html', output / f'courses/{article["id"]}/lab/index.html', '../../../', course=article)
    shutil.copytree(ROOT / 'static', output / 'static', dirs_exist_ok=True,
                    ignore=shutil.ignore_patterns('__pycache__', '*.pyc'))
    generated_assets = {name: data for article in articles for name, data in article.get('assets', {}).items()}
    asset_manifest = output / '.generated-assets.json'
    if asset_manifest.exists():
        for name in set(json.loads(asset_manifest.read_text(encoding='utf-8'))) - generated_assets.keys():
            target = (output / name).resolve()
            if not any(target.is_relative_to((output / area).resolve()) for area in ('static/reports', 'static/experiments')):
                raise ValueError('Invalid generated image path')
            target.unlink(missing_ok=True)
    for name, data in generated_assets.items():
        target = output / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    asset_manifest.write_text(json.dumps(sorted(generated_assets)), encoding='utf-8')
    (output / '.nojekyll').touch()
    manifest.write_text(json.dumps(sorted(expected_pages)), encoding='utf-8')
    print(f'Built {len(articles)} published lesson(s): {output}')


if __name__ == '__main__':
    build()
    with ZipFile(ROOT / 'github-pages-ready.zip', 'w', ZIP_DEFLATED) as archive:
        for file in OUTPUT.rglob('*'):
            if file.is_file() and not file.name.startswith('.generated-'):
                archive.write(file, file.relative_to(OUTPUT))
    print('Created github-pages-ready.zip')
